"use client";
import {useEffect,useState} from 'react';
import {fetchJson} from '../lib/api';
import Onboarding from '../lib/onboarding';
import {AcademicReader,AcademicQueue} from '../lib/academic-reader';

type Course={id:string;name:string;section_code:string;project_id:string;syllabus?:{raw_text:string}};
type Row={course_code:string;name:string;section_code:string;weekday:number;start:string;end:string;weeks:number[];location:string;teacher:string;canvas_id:string};
const emptyRow:Row={course_code:'',name:'',section_code:'default',weekday:0,start:'08:00',end:'09:40',weeks:[1],location:'',teacher:'',canvas_id:''};
const send=(path:string,body:unknown={},method='POST')=>fetchJson<any>(path,{method,body:JSON.stringify(body),signal:AbortSignal.timeout(660000)});
const pretty=(v:unknown)=>JSON.stringify(v,null,2);
export default function Home(){
 const [showOnboarding,setShowOnboarding]=useState(false);
 const [tab,setTab]=useState('课程'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false);
 const [settings,setSettings]=useState<any>({}),[courses,setCourses]=useState<Course[]>([]),[course,setCourse]=useState<any>(null),[detailTab,setDetailTab]=useState('复盘');
 const [tasks,setTasks]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]),[pending,setPending]=useState<any[]>([]),[groups,setGroups]=useState<any[]>([]);
 const [title,setTitle]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10));
 const [setup,setSetup]=useState<any>({storage_root:'',term_name:'新学期',starts_on:'',teaching_weeks:18,periods:[],replay_mode:'text'});
 const [periods,setPeriods]=useState('[]'),[rows,setRows]=useState<Row[]>([{...emptyRow}]),[warnings,setWarnings]=useState<string[]>([]),[reviewed,setReviewed]=useState(false);
 const [ai,setAi]=useState<any>({provider:'none',base_url:'http://127.0.0.1:11434',text_model:'qwen3:8b',vision_model:'',api_key:'',cloud_consent:false});
 const [identity,setIdentity]=useState<any>(null),[connections,setConnections]=useState<any>({}),[accounts,setAccounts]=useState<any[]>([]),[components,setComponents]=useState<any>({});
 const [wecom,setWecom]=useState<any>({account_id:'',organization_id:'',expected_name:'',expected_organization:'上海财经大学'});
 async function refresh(){const [s,c,t,e,p,g]=await Promise.all([fetchJson<any>('/api/setup'),fetchJson<Course[]>('/api/academics/courses'),fetchJson<any[]>('/api/tasks'),fetchJson<any[]>('/api/calendar'),fetchJson<any[]>('/api/academics/review'),fetchJson<any[]>('/api/academics/wecom/chat-candidates')]);setSettings(s);setCourses(c);setTasks(t);setEvents(e);setPending(p);setGroups(g);return s}
 async function act(fn:()=>Promise<unknown>,message='已完成'){setBusy(true);setError('');setNotice('');try{await fn();setNotice(message)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 useEffect(()=>{void act(async()=>{const hash=new URLSearchParams(location.hash.slice(1)),token=hash.get('token');if(token){await fetch('/session',{method:'POST',headers:{'x-personal-os-token':token}}).then(r=>{if(!r.ok)throw Error('登录凭据无效')});history.replaceState(null,'',location.pathname)}const s=await refresh();setSetup({...setup,...s.settings,storage_root:s.settings.storage_root||s.default_storage_root});setPeriods(pretty(s.settings.periods||[]));setAi({...ai,...s.settings.ai,api_key:''});setWecom({...wecom,...s.settings.wecom});const onboarding=await fetchJson<any>('/api/onboarding');setShowOnboarding(!onboarding.completed);if(!s.configured)setTab('设置');setReady(true)},'');},[]);
 async function openCourse(id:string){setCourse(await fetchJson<any>(`/api/academics/courses/${id}?lightweight=true`));setDetailTab('复盘')}
 async function loadConnections(){const [c,k,i,a,co]=await Promise.all([fetchJson<any>('/api/academics/canvas/status'),fetchJson<any>('/api/academics/kzkt/status'),fetchJson<any>('/api/connections/canvas/identity'),fetchJson<any[]>('/api/connections/wecom/accounts'),fetchJson<any>('/api/components')]);setConnections({canvas:c,kzkt:k});setIdentity(i);setAccounts(a);setComponents(co)}
 function edit(i:number,k:keyof Row,v:any){setRows(r=>r.map((x,j)=>j===i?{...x,[k]:v}:x));setReviewed(false)}
 async function preview(){const r=await send('/api/setup/timetable/preview',{rows});setRows(r.rows);setWarnings(r.warnings);setReviewed(true)}
 async function recognize(file:File){const data=await new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result));r.onerror=no;r.readAsDataURL(file)});const result=await send('/api/setup/timetable/recognize',{image:data});setRows(result.rows);setWarnings([...result.warnings,result.notice]);setReviewed(false)}
 if(ready&&showOnboarding)return <Onboarding onDone={async()=>{const s=await refresh();setSetup({...setup,...s.settings,storage_root:s.settings.storage_root||s.default_storage_root});setPeriods(pretty(s.settings.periods||[]));setAi({...ai,...s.settings.ai,api_key:''});setShowOnboarding(false);setTab('课程')}}/>;
 return <div className="app"><aside className="sidebar"><a className="brand" href="#" onClick={e=>e.preventDefault()}><b>上财学业助手</b><small>SUFE STUDY ASSISTANT</small></a><nav>{['课程','日历','待办','处理任务','待确认','连接','设置'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);if(t==='连接')void act(loadConnections,'')}}>{t}</button>)}</nav><footer>开发预览版<br/>本地保存 · 自己掌握<br/><a href="https://github.com/y09749204-gif/sufe-study-assistant" target="_blank" rel="noreferrer">项目源码 ↗</a></footer></aside>
 <main className="workspace"><header className="top"><div><span className="eyebrow">学习工作台</span><h1>{tab}</h1></div><button disabled={busy} onClick={()=>void act(refresh,'已刷新')}>{busy?'处理中…':'刷新'}</button></header>{error&&<p className="alert" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}{!ready&&!error&&<p>正在连接本机服务…</p>}
 {ready&&tab==='课程'&&<><div className="course-list">{courses.map(c=><button key={c.id} className={course?.id===c.id?'selected':''} onClick={()=>void act(()=>openCourse(c.id),'')}><strong>{c.name}</strong><small>教学班 {c.section_code}</small></button>)}</div>{!courses.length&&<section><h2>从自己的课表开始</h2><p>在设置中选择学期，再手动录入、导入模板或识别课表截图。</p><button onClick={()=>setTab('设置')}>配置课表</button></section>}{course&&<section><div className="section-head"><h2>{course.name}</h2><select aria-label="本课程回放模式" value={settings.settings?.course_modes?.[course.id]||'default'} onChange={e=>void act(async()=>{await send(`/api/setup/courses/${course.id}/mode`,{mode:e.target.value},'PUT');await refresh()})}><option value="default">跟随全局模式</option><option value="text">文本模式</option><option value="illustrated">图文模式</option></select></div><div className="tabs">{['复盘','资料','大纲','课程消息'].map(t=><button className={detailTab===t?'selected':''} onClick={()=>setDetailTab(t)} key={t}>{t}</button>)}</div>{detailTab==='复盘'&&<AcademicReader courseId={course.id} recordings={course.recordings||[]} onConfirmSlide={async(id,page)=>{await send(`/api/academics/recording-slides/${id}/confirm`,{courseware_page_id:page})}} onResolve={async(id,action)=>{await send(`/api/academics/review/${id}/resolve?action=${action}`,{});await refresh()}}/>}{detailTab==='资料'&&<>{!(course.resources||[]).length&&<p>同步 Canvas 或企微后，课程资料会出现在这里。</p>}{(course.resources||[]).map((r:any)=><article key={r.id}><strong>{r.title}</strong><span>{r.availability}</span>{r.availability==='available'?<a href={`/api/academics/resources/${r.id}/file`} target="_blank" rel="noreferrer">打开文件</a>:<button disabled={busy} onClick={()=>void act(()=>send(`/api/academics/wecom/resources/${r.id}/recheck`),'已重新检查缓存')}>重新检查</button>}</article>)}</>}{detailTab==='大纲'&&<pre>{course.syllabus?.raw_text||'尚未同步大纲'}</pre>}{detailTab==='课程消息'&&(course.messages||[]).map((m:any)=><article key={m.id}><strong>{m.sender_name}</strong><p>{m.text}</p></article>)}</section>}</>}
 {ready&&tab==='日历'&&<section><div className="section-head"><h2>每日安排</h2><input aria-label="查看日期" type="date" value={date} onInput={e=>setDate(e.currentTarget.value)}/></div>{events.filter(e=>e.start_at&&new Date(e.start_at).toLocaleDateString('en-CA')===date).map(e=><article key={e.id}><time>{new Date(e.start_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}—{new Date(e.end_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time><strong>{e.title}</strong><span>{e.locked?'固定课程':'日程'}</span></article>)}{!events.some(e=>e.start_at&&new Date(e.start_at).toLocaleDateString('en-CA')===date)&&<p>这一天还没有安排。</p>}<details><summary>添加日程</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{await send('/api/calendar',{title:f.get('title'),item_type:'hard_event',start_at:new Date(String(f.get('start'))).toISOString(),end_at:new Date(String(f.get('end'))).toISOString()});await refresh()})}}><label>标题<input name="title" required/></label><label>开始<input name="start" type="datetime-local" required/></label><label>结束<input name="end" type="datetime-local" required/></label><button disabled={busy}>添加</button></form></details></section>}
 {ready&&tab==='待办'&&<section><form className="inline" onSubmit={e=>{e.preventDefault();void act(async()=>{await send('/api/tasks',{title});setTitle('');await refresh()})}}><input aria-label="新待办" placeholder="添加一项学习任务" value={title} onChange={e=>setTitle(e.target.value)} required/><button disabled={busy}>添加</button></form>{tasks.map(t=><article key={t.id}><input aria-label={`完成 ${t.title}`} type="checkbox" checked={t.status==='done'} onChange={e=>void act(async()=>{await send(`/api/tasks/${t.id}`,{status:e.target.checked?'done':'todo'},'PATCH');await refresh()})}/><div><strong>{t.title}</strong><small>{t.deadline_at?new Date(t.deadline_at).toLocaleString('zh-CN'):'未设置截止时间'}</small>{t.description&&<p>{t.description}</p>}</div></article>)}</section>}
 {ready&&tab==='处理任务'&&<AcademicQueue/>}
 {ready&&tab==='待确认'&&<section><h2>先核对，再加入安排</h2>{!pending.length&&!groups.length&&<p>暂时没有待确认事项。</p>}{groups.map(g=><article key={g.id}><div><strong>{g.payload.course_name}</strong><p>{g.payload.conversation_name}</p></div><button disabled={busy} onClick={()=>void act(async()=>{await send(`/api/academics/wecom/chat-candidates/${g.id}/confirm`);await refresh()})}>绑定课程群</button><button onClick={()=>void act(async()=>{await send(`/api/academics/wecom/chat-candidates/${g.id}/dismiss`);await refresh()})}>忽略</button></article>)}{pending.map(p=><article key={p.id}><div><strong>{p.payload.course_name}</strong><p>{p.payload.raw_text||p.payload.evidence||p.payload.title}</p></div>{['accept','reject'].map(a=><button key={a} disabled={busy} onClick={()=>void act(async()=>{await send(`/api/academics/review/${p.id}/resolve?action=${a}`,{});await refresh()})}>{a==='accept'?'确认':'忽略'}</button>)}</article>)}</section>}
 {ready&&tab==='连接'&&<><section><h2>Canvas</h2><p>先登录，再读取身份并核对绑定。登录资料仅保存在本应用的独立浏览器目录。</p><div className="toolbar"><button disabled={busy} onClick={()=>void act(()=>send('/api/connections/canvas/login'),'登录窗口已启动；完成后刷新状态')}>登录</button><button disabled={busy} onClick={()=>void act(()=>send('/api/connections/canvas/identify'),'正在读取身份；稍后刷新状态')}>读取身份</button><button onClick={()=>void act(loadConnections,'已刷新连接状态')}>刷新状态</button><button disabled={busy||!settings.settings?.canvas_user_id} onClick={()=>void act(()=>send('/api/academics/canvas/run'),'同步已启动')}>同步课程</button></div>{identity?.user_id&&<p>当前识别：{identity.name}（{identity.user_id}） <button onClick={()=>void act(async()=>{await send('/api/connections/canvas/bind',{user_id:identity.user_id});await refresh()})}>确认这是我的账号</button></p>}<pre>{pretty(connections.canvas||{})}</pre></section><section><h2>空中课堂</h2><p>仅处理“我参与的”且能匹配本学期课表的回放。</p><button disabled={busy} onClick={()=>void act(()=>send('/api/connections/kzkt/login'),'登录窗口已启动')}>登录空中课堂</button><button onClick={()=>setTab('处理任务')}>查看回放处理</button><pre>{pretty(connections.kzkt||{})}</pre></section><section><h2>企业微信 · 本机只读采集</h2><p>只操作你自己的已登录客户端。底层会读取本机数据库副本以发现会话；确认绑定后才导入课程消息。无界面附件下载仍在研究，未缓存文件请先在企微下载。</p><form onSubmit={e=>{e.preventDefault();void act(()=>send('/api/connections/wecom',wecom,'PUT'))}}><label>本机账号<select value={wecom.account_id} required onChange={e=>setWecom({...wecom,account_id:e.target.value})}><option value="">请选择</option>{accounts.map(a=><option key={a.account_id}>{a.account_id}</option>)}</select></label>{[['organization_id','组织 ID'],['expected_name','本人姓名'],['expected_organization','组织名称']].map(([k,l])=><label key={k}>{l}<input value={wecom[k]} required onChange={e=>setWecom({...wecom,[k]:e.target.value})}/></label>)}<button disabled={busy}>保存身份配置</button></form><div className="toolbar"><button disabled={busy} onClick={()=>void act(()=>send('/api/connections/wecom/discover-key'),'密钥已加密保存；请同步以核验身份')}>读取并保护本机密钥</button><button disabled={busy} onClick={()=>void act(async()=>{await send('/api/academics/wecom/sync');await refresh()})}>只读同步</button></div></section></>}
 {ready&&tab==='设置'&&<><section><h2>首次设置向导</h2><p>重新查看学期、平台连接与学习功能；已有课程不会被清空。</p><button onClick={()=>setShowOnboarding(true)}>重新打开设置向导</button></section><section><h2>学期与存储</h2><form onSubmit={e=>{e.preventDefault();void act(async()=>{await send('/api/setup',{...setup,periods:JSON.parse(periods)});await refresh()})}}><label>资料目录<input required value={setup.storage_root} onChange={e=>setSetup({...setup,storage_root:e.target.value})}/></label><div className="form-grid"><label>学期名称<input required value={setup.term_name} onChange={e=>setSetup({...setup,term_name:e.target.value})}/></label><label>第一周周一<input required type="date" value={setup.starts_on} onInput={e=>setSetup({...setup,starts_on:e.currentTarget.value})}/></label><label>教学周数<input type="number" min="1" max="52" value={setup.teaching_weeks} onChange={e=>setSetup({...setup,teaching_weeks:Number(e.target.value)})}/></label><label>回放处理模式<select value={setup.replay_mode} onChange={e=>setSetup({...setup,replay_mode:e.target.value})}><option value="text">文本：不下载视频</option><option value="illustrated">图文：下载视频并提取画面</option></select></label></div><details><summary>节次时间（用于课表截图识别）</summary><p>格式：[{`"number":1,"start":"08:00","end":"08:45"`}]，请按实际课表填写。</p><textarea aria-label="节次 JSON" value={periods} onChange={e=>setPeriods(e.target.value)}/></details><button disabled={busy}>保存学期设置</button></form></section>
 <section><h2>导入自己的课表</h2><p>星期以周一为 0、周日为 6。周数用逗号分隔；单双周请填写实际周序号。所有导入都需核对后确认。</p><div className="toolbar"><a href="/timetable-template.csv" download>下载 CSV 模板</a><label className="file-button">导入 CSV<input type="file" accept=".csv" onChange={e=>{const f=e.target.files?.[0];if(f)void act(async()=>{const r=await send('/api/setup/timetable/csv',{text:await f.text()});setRows(r.rows);setWarnings(r.warnings);setReviewed(false)},'已载入草稿，请核对')}}/></label><label className="file-button">识别截图<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void act(()=>recognize(f),'已识别，请逐项核对')}}/></label></div><div className="table-scroll"><table><thead><tr>{['课程编号','课程名称','教学班','星期','开始','结束','周数','地点','教师','Canvas ID',''].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{(['course_code','name','section_code','weekday','start','end','weeks','location','teacher','canvas_id'] as (keyof Row)[]).map(k=><td key={k}><input aria-label={`${i+1} 行 ${k}`} value={Array.isArray(r[k])?(r[k] as number[]).join(','):r[k]} onChange={e=>edit(i,k,k==='weeks'?e.target.value.split(',').filter(Boolean).map(Number):k==='weekday'?Number(e.target.value):e.target.value)}/></td>)}<td><button onClick={()=>{setRows(rows.filter((_,j)=>j!==i));setReviewed(false)}}>删除</button></td></tr>)}</tbody></table></div><div className="toolbar"><button onClick={()=>{setRows([...rows,{...emptyRow}]);setReviewed(false)}}>添加一行</button><button disabled={busy||!settings.configured} onClick={()=>void act(preview,'校验完成，请核对预览')}>校验课表</button><button disabled={busy||!reviewed} onClick={()=>void act(async()=>{const result=await send('/api/setup/timetable/confirm',{rows});await refresh();setReviewed(false);setNotice(`已生成 ${result.created_sessions} 节课`)},'已导入课表')}>已核对，确认导入</button></div>{warnings.map((w,i)=><p className="notice" key={i}>{w}</p>)}</section>
 <section><h2>AI · 可以暂不开启</h2><form onSubmit={e=>{e.preventDefault();void act(async()=>{await send('/api/setup/ai',ai,'PUT');setAi({...ai,api_key:''});await refresh()})}}><label>运行方式<select value={ai.provider} onChange={e=>setAi({...ai,provider:e.target.value,base_url:e.target.value==='ollama'?'http://127.0.0.1:11434':'https://api.openai.com/v1',cloud_consent:false})}><option value="none">不开启 AI</option><option value="ollama">本机 Ollama</option><option value="openai">自己的 OpenAI 兼容 API</option></select></label>{ai.provider!=='none'&&<><label>服务地址<input required value={ai.base_url} onChange={e=>setAi({...ai,base_url:e.target.value,cloud_consent:false})}/></label><label>文字模型<input required value={ai.text_model} onChange={e=>setAi({...ai,text_model:e.target.value})}/></label><label>看图模型（截图识别需要）<input value={ai.vision_model} onChange={e=>setAi({...ai,vision_model:e.target.value})}/></label>{ai.provider==='openai'&&<><label>API Key<input type="password" autoComplete="off" placeholder={settings.api_key_set?'已保存；留空保留':'请输入自己的 API Key'} value={ai.api_key} onChange={e=>setAi({...ai,api_key:e.target.value})}/></label><label className="check"><input type="checkbox" checked={ai.cloud_consent} onChange={e=>setAi({...ai,cloud_consent:e.target.checked})}/>我同意将待处理课堂文本／课表截图发送至 {ai.base_url}，并自行承担服务费用。</label></>}</>}<button disabled={busy}>保存 AI 设置</button><button type="button" disabled={busy||ai.provider==='none'} onClick={()=>void act(()=>send('/api/setup/ai/test'),'模型连接与 JSON 输出验证通过')}>测试已保存的配置</button></form></section>
 <section><h2>可选组件</h2><p>模型和语音转写组件不随安装包强制下载。</p><div className="toolbar"><a href="https://ollama.com/download/windows" target="_blank" rel="noreferrer">安装 Ollama ↗</a><a href="https://www.libreoffice.org/download/download-libreoffice/" target="_blank" rel="noreferrer">安装 LibreOffice ↗</a><button onClick={()=>void act(async()=>setComponents(await fetchJson('/api/components')),'已检测')}>检测组件</button></div><pre>{pretty(components)}</pre><details><summary>安装本地 Whisper 转写</summary><p>下载 small 模型和依赖可能占用数 GB；CPU 可运行但较慢。仅在没有平台文本时使用。</p><button disabled={busy} onClick={()=>void act(()=>send('/api/components/whisper',{model:'small',device:'auto',download_confirmed:true}),'下载已启动，请查看安装状态')}>下载并启用本地转写</button><button onClick={()=>void act(async()=>setComponents(await fetchJson('/api/components/whisper')),'已刷新安装状态')}>查看安装状态</button></details></section></>}
 </main></div>
}
