"use client";
import {useEffect, useState} from "react";
import ReactMarkdown from "react-markdown";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import "katex/dist/katex.min.css";
import {apiBase, fetchJson} from "./api";
import "./academic-reader.css";
import {ClassroomRequirementCard, type ClassroomRequirement} from "./classroom-requirement";

type Slide={id:string;start_seconds:number;end_seconds:number;status:string;confidence:number;capture_image_url:string|null;courseware_page:{page_number:number;title:string;image_url:string}|null;candidates:{courseware_page_id:string;page_number:number;title:string;confidence:number}[]};
type Segment={title:string;summary:string;start_seconds:number|null;key_concepts?:string[];teacher_emphasis?:string[]};
type Brief={id:string;title:string;taught_at?:string|null;availability:string;error?:string|null};
type Attendance={status:string;signals:{kind:string;text:string;evidence:string;timestamp_seconds:number|null}[]};
type Detail=Brief&{attendance?:Attendance;source_url:string|null;review:{summary:{overall_summary?:string;segments?:Segment[];content_checks?:{status:string;findings:string[]}}}|null;transcript:{text:string}|null;slide_segments:Slide[];requirements:ClassroomRequirement[]};
const stamp=(s:number|null)=>s==null?"时间未知":`${Math.floor(s/60).toString().padStart(2,"0")}:${Math.floor(s%60).toString().padStart(2,"0")}`;
const labels:Record<string,string>={success:"处理完成",superseded:"已由新版替代",queued:"排队中",running:"处理中",retry_wait:"等待重试",failed:"失败",blocked:"等待依赖恢复",needs_confirmation:"待确认",review_ready:"复盘已生成",downloaded:"已下载",discovered:"待下载",media_expired:"媒体已过期",discover:"发现回放",download:"下载",review:"转写与复盘",slides:"提取课堂画面",requirements:"提取课堂要求",complete:"处理完成"};
function Markdown({text}:{text:string}){return <div className="lesson-markdown"><ReactMarkdown remarkPlugins={[remarkMath]} rehypePlugins={[[rehypeKatex,{throwOnError:false,strict:false,trust:false}]]} skipHtml>{text}</ReactMarkdown></div>}
function Picture({src,alt,onClick}:{src:string;alt:string;onClick?:()=>void}){const [failed,setFailed]=useState(false);const [version,setVersion]=useState(0);useEffect(()=>setFailed(false),[src]);return failed?<button className="image-retry" onClick={()=>{setFailed(false);setVersion(v=>v+1)}}>图片加载失败 · 重试</button>:<img key={version} loading="lazy" src={`${apiBase}${src}${version?`?retry=${version}`:""}`} alt={alt} onError={()=>setFailed(true)} onClick={onClick} tabIndex={onClick?0:undefined} onKeyDown={e=>{if(e.key==="Enter")onClick?.()}}/>}
export function AcademicReader({courseId,recordings,onConfirmSlide,onResolve}:{courseId:string;recordings:Brief[];onConfirmSlide:(id:string,page:string|null)=>Promise<void>;onResolve:(id:string,action:"accept"|"reject")=>Promise<void>}){
 const [selected,setSelected]=useState("");const [lesson,setLesson]=useState<Detail|null>(null);const [error,setError]=useState("");const [active,setActive]=useState(0);const [lightbox,setLightbox]=useState<number|null>(null);const [compare,setCompare]=useState<Slide|null>(null);const [busy,setBusy]=useState(false);
 const sorted=[...recordings].sort((a,b)=>(b.taught_at||"").localeCompare(a.taught_at||""));
 useEffect(()=>{const saved=localStorage.getItem(`lesson:${courseId}`);setSelected(recordings.some(r=>r.id===saved)?saved!:sorted[0]?.id||"");setLesson(null)},[courseId,recordings.map(r=>r.id).join(",")]);
 async function load(){if(selected){setLesson(await fetchJson<Detail>(`/api/academics/recordings/${selected}`))}}
 useEffect(()=>{let cancelled=false;setLesson(null);setError("");if(selected){localStorage.setItem(`lesson:${courseId}`,selected);fetchJson<Detail>(`/api/academics/recordings/${selected}`).then(d=>{if(!cancelled){setLesson(d);const n=Number(localStorage.getItem(`segment:${selected}`)||0);setActive(n);if(n>0)setTimeout(()=>document.getElementById(`lesson-segment-${n}`)?.scrollIntoView({block:"start"}),100)}}).catch(e=>!cancelled&&setError(e.message))}return()=>{cancelled=true}},[selected]);
 useEffect(()=>{if(lightbox==null&&!compare)return;const handler=(e:KeyboardEvent)=>{if(e.key==="Escape"){setLightbox(null);setCompare(null)}if(e.key==="Tab"){const buttons=[...document.querySelectorAll<HTMLButtonElement>(".lesson-lightbox button:not(:disabled)")];const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}if(lightbox==null)return;if(e.key==="ArrowRight")setLightbox(n=>Math.min((lesson?.slide_segments.length||1)-1,(n||0)+1));if(e.key==="ArrowLeft")setLightbox(n=>Math.max(0,(n||0)-1))};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[lightbox,lesson,compare]);
 const segments=lesson?.review?.summary.segments||[];const slides=lesson?.slide_segments||[];
 const indexFor=(slide:Slide)=>{let found=-1;segments.forEach((s,i)=>{if(s.start_seconds!=null&&s.start_seconds<=slide.start_seconds&&(found<0||s.start_seconds>=(segments[found].start_seconds??-1)))found=i});return found};
 const imagesFor=(i:number)=>{const start=segments[i].start_seconds;if(start==null)return [];const next=segments.slice(i+1).find(s=>s.start_seconds!=null&&s.start_seconds>start)?.start_seconds??Infinity;return slides.filter(s=>s.start_seconds<next&&s.end_seconds>start)};
 const source=(s:Slide)=>s.status==="confirmed"?s.courseware_page?.image_url||s.capture_image_url:s.capture_image_url;
 function jump(i:number){setActive(i);localStorage.setItem(`segment:${selected}`,String(i));document.getElementById(`lesson-segment-${i}`)?.scrollIntoView({behavior:"smooth",block:"start"})}
 async function action(fn:()=>Promise<void>){setBusy(true);setError("");try{await fn();await load()}catch(e){setError(String(e))}finally{setBusy(false)}}
 function gallery(items:Slide[]){return <div className="lesson-gallery">{items.map(slide=><figure key={slide.id}>{source(slide)?<Picture src={source(slide)!} alt={`课堂画面 ${stamp(slide.start_seconds)}`} onClick={()=>setLightbox(slides.findIndex(s=>s.id===slide.id))}/>:<p>画面暂不可用</p>}<figcaption><span>{stamp(slide.start_seconds)} · {slide.status==="confirmed"?"已关联课件":slide.status==="pending"?"关联待确认":"未关联 · 课堂截图"}</span>{slide.status==="pending"&&<button onClick={()=>setCompare(slide)}>对照候选</button>}</figcaption></figure>)}</div>}
 return <div className="lesson-workspace"><label className="lesson-picker">选择课次<select value={selected} onChange={e=>setSelected(e.target.value)}>{sorted.map(r=><option key={r.id} value={r.id}>{r.taught_at?new Date(r.taught_at).toLocaleDateString("zh-CN"):"日期待确认"} · {r.title} · {labels[r.availability]||r.availability}</option>)}</select></label>{error&&<p role="alert">{error} <button onClick={()=>void load()}>重试</button></p>}{!sorted.length?<p className="empty">尚无回放，可在“处理任务”中查看发现进度。</p>:!lesson?<p>正在加载这一节课…</p>:<>
 <header className="lesson-heading"><div><p className="eyebrow">LESSON REVIEW</p><h3>{lesson.title}</h3><small>{labels[lesson.availability]||lesson.availability} · {segments.length} 段笔记 · {slides.length} 段画面</small></div>{lesson.source_url&&<a href={lesson.source_url} target="_blank" rel="noreferrer">打开原回放 ↗</a>}</header>
 <div className="lesson-reading"><details className="lesson-directory" open><summary>本节目录</summary><nav>{segments.map((s,i)=><button key={i} className={active===i?"active":""} onClick={()=>jump(i)}><small>{stamp(s.start_seconds)}</small>{s.title}</button>)}<a href="#lesson-attendance">签到与点名</a><a href="#lesson-all-images">全部课堂画面</a><a href="#lesson-requirements">课堂要求</a></nav></details>
 <main className="lesson-body"><section id="lesson-attendance" className="lesson-overview"><h3>签到与点名 · 重点核查</h3><p>记录老师是否提到发起签到、查签到／点名及签到要求。字幕无法证明你本人已经签到。</p>{!lesson.attendance?.signals.length?<p>{!lesson.transcript?"尚无字幕，暂无法判断。":"未找到明确关键词证据；不代表本节没有签到。"}</p>:lesson.attendance.signals.map((signal,i)=><details key={i}><summary>{stamp(signal.timestamp_seconds)} · {({requirement:"签到／考勤要求线索",checking:"查签到／点名线索",initiated:"发起签到线索",negative:"含未签到／无需签到等否定表述",example:"举例或假设",mentioned:"签到相关提及，待核实"} as Record<string,string>)[signal.kind]}</summary><p>{signal.text}</p><blockquote>{signal.evidence}</blockquote></details>)}<p>需要办理的要求见下方“课堂要求”，核对后再确认生成待办。</p></section>{lesson.review?<><div className="lesson-overview"><h4>本节概览</h4><Markdown text={(lesson.review.summary.overall_summary||"").split(/\n\s*\n/)[0]||"暂无概览"}/><details><summary>完整摘要</summary><Markdown text={lesson.review.summary.overall_summary||""}/></details>{lesson.review.summary.content_checks&&<details><summary>{lesson.review.summary.content_checks.status==="corrected"?"已按原文校订 · 查看记录":"内容仍需核对"}</summary>{lesson.review.summary.content_checks.findings.map((f,i)=><p key={i}>{f}</p>)}</details>}</div>{segments.map((segment,i)=><article className="lesson-segment" id={`lesson-segment-${i}`} key={i} onMouseEnter={()=>{setActive(i);localStorage.setItem(`segment:${selected}`,String(i))}}><div className="segment-heading"><span>{String(i+1).padStart(2,"0")} / {stamp(segment.start_seconds)}</span><h3>{segment.title}</h3></div><Markdown text={segment.summary}/>{!!segment.key_concepts?.length&&<div className="concepts">{segment.key_concepts.map((c,j)=><Markdown text={c} key={j}/>)}</div>}{!!segment.teacher_emphasis?.length&&<aside className="teacher-emphasis"><strong>课堂强调</strong><Markdown text={segment.teacher_emphasis.map(t=>`- ${t}`).join("\n")}/></aside>}{gallery(imagesFor(i))}</article>)}</>:<p>{lesson.error||"复盘尚未生成，请查看处理任务。"}</p>}
 <section id="lesson-all-images"><h3>全部课堂画面 <small>{slides.length}</small></h3><p>包含未归入笔记的画面；未确认的匹配显示实际截图。</p><details><summary>展开画面总览</summary>{gallery(slides)}</details>{slides.some(s=>indexFor(s)<0)&&<><h4>未归入笔记的画面</h4>{gallery(slides.filter(s=>indexFor(s)<0))}</>}</section>
 <section id="lesson-requirements"><h3>课堂要求</h3>{!lesson.requirements?.length&&<p>本节没有识别到明确要求。</p>}{lesson.requirements?.map(r=><ClassroomRequirementCard key={r.id} item={r} onResolve={(id,choice)=>action(()=>onResolve(id,choice))} onChanged={load}/>)}</section><details><summary>原始字幕</summary><pre className="lesson-transcript">{lesson.transcript?.text||"尚无字幕"}</pre></details></main></div></>}
 {lightbox!=null&&slides[lightbox]&&<div className="lesson-lightbox" role="dialog" aria-modal="true" aria-label="课堂画面放大" onClick={()=>setLightbox(null)}><div onClick={e=>e.stopPropagation()}><header><button onClick={()=>setLightbox(Math.max(0,lightbox-1))} disabled={lightbox===0}>上一张</button><span>{lightbox+1}/{slides.length} · {stamp(slides[lightbox].start_seconds)}</span><button onClick={()=>setLightbox(Math.min(slides.length-1,lightbox+1))} disabled={lightbox===slides.length-1}>下一张</button><button autoFocus onClick={()=>setLightbox(null)}>关闭</button></header>{source(slides[lightbox])&&<Picture src={source(slides[lightbox])!} alt="课堂画面放大"/>}</div></div>}
 {compare&&<div className="lesson-lightbox" role="dialog" aria-modal="true" aria-label="课件匹配对照"><div className="comparison"><header><h3>对照课件候选</h3><button autoFocus onClick={()=>setCompare(null)}>关闭</button></header><p>左侧为实际课堂画面，右侧为待确认候选。</p>{compare.candidates.map((c,i)=><section key={c.courseware_page_id}><div className="comparison-images">{source(compare)&&<Picture src={source(compare)!} alt="实际课堂截图"/>}<Picture src={`/api/academics/courseware-pages/${c.courseware_page_id}/image`} alt={`候选课件第${c.page_number}页`}/></div><p>候选 {i+1} · 第 {c.page_number} 页 · 匹配度 {Math.round(c.confidence*100)}%</p><button disabled={busy} onClick={()=>void action(async()=>{await onConfirmSlide(compare.id,c.courseware_page_id);setCompare(null)})}>确认这一页</button></section>)}</div></div>}
 </div>
}

type Queue={paused:boolean;counts:Record<string,number>;progress:Record<string,number|string>;tasks:{id:string;title:string;kind:string;stage:string;status:string;attempt:number;error:string|null;recording_id:string|null;result:Record<string,unknown>;batches:string[]}[]};
export function AcademicQueue(){const [data,setData]=useState<Queue|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [batch,setBatch]=useState("");async function load(){setData(await fetchJson<Queue>("/api/academics/kzkt/queue"))}useEffect(()=>{void load().catch(e=>setError(e.message));const timer=setInterval(()=>void load().catch(e=>setError(e.message)),5000);return()=>clearInterval(timer)},[]);async function act(action:string){setBusy(true);setError("");try{const result=await fetchJson<{batch_id?:string}>(`/api/academics/kzkt/queue/${action}`,{method:"POST",body:JSON.stringify({})});if(result.batch_id)setBatch(result.batch_id);await load()}catch(e){setError(String(e))}finally{setBusy(false)}}return <section className="academic-queue"><header><div><h2>回放处理任务</h2><p>本学期 · 非体育课程 · 最新优先 · 串行执行</p></div><div className="toolbar"><button disabled={busy} onClick={()=>void act("batches")}>发现并排入全部回放</button><button disabled={busy} onClick={()=>void act(data?.paused?"resume":"pause")}>{data?.paused?"恢复处理":"完成当前阶段后暂停"}</button><button disabled={busy} onClick={()=>void act("retry")}>重试失败项</button></div></header>{error&&<p role="alert">{error}</p>}{batch&&<p>已创建批次：{batch}</p>}<div className="queue-counts">{Object.entries(data?.counts||{}).map(([s,n])=><span key={s}>{labels[s]} <b>{n}</b></span>)}</div>{data?.paused&&<p className="notice">队列已暂停；正在运行的阶段结束后停止。</p>}<p>“处理完成”表示文件和复盘已生成，不代表内容已逐节抽查。课堂要求仍需确认。</p><div className="queue-table">{data?.tasks.map(t=><article key={t.id}><div><strong>{t.title}</strong><small>{t.kind==="discovery"?"课程回放发现":t.kind==="requirements"?"课堂要求补提取":"课堂处理"} · {labels[t.stage]||t.stage}</small></div><span className={`queue-status ${t.status}`}>{labels[t.status]||t.status}</span>{t.status==="running"&&<small>{data.progress.current||0}/{data.progress.total||"—"} · {data.progress.percent||0}%</small>}{t.error&&<details><summary>失败原因</summary><p role="status">{t.error}</p></details>}{["failed","retry_wait","blocked"].includes(t.status)&&<button disabled={busy} onClick={()=>void act(`tasks/${t.id}/retry`)}>重试此项</button>}{t.kind==="discovery"&&t.result.discovered!=null&&<small>发现 {String(t.result.discovered)} · 新入队 {String(t.result.enqueued)} · 复用 {String(t.result.reused)} · 待确认 {String(t.result.needs_confirmation)}</small>}</article>)}</div>{!data?.tasks.length&&<p>暂无后台处理任务。</p>}</section>}


export function AcademicPendingLinks({onOpen}:{onOpen:(courseId:string,recordingId:string)=>void}){const [items,setItems]=useState<{recording_id:string;course_id:string;title:string;count:number}[]>([]);const [error,setError]=useState("");useEffect(()=>{fetchJson<typeof items>("/api/academics/kzkt/queue/pending-slides").then(setItems).catch(e=>setError(e.message))},[]);return <section className="academic-notices"><h2>课件关联待确认</h2>{error&&<p role="alert">{error}</p>}{items.map(item=><article key={item.recording_id}><strong>{item.title}</strong><p>{item.count} 段课堂画面需要与候选课件对照。</p><button onClick={()=>onOpen(item.course_id,item.recording_id)}>进入课次查看</button></article>)}{!items.length&&!error&&<p>暂无待确认的课件关联。</p>}</section>}
